run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

issues:
  new: false
  fix: true
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - varnamelen
        - funlen
        - gosec
        - goconst
        - cyclop
        - containedctx

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # nondefault
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  fast: false

linters-settings:
  varnamelen:
    ignore-names:
      - i
      - db # database
      - id # identifier
      - wg # wait group
      - fn # function
      - ok # ok
      - tx # transaction
      - cb # callback
